version: 2.1
orbs:
  node: circleci/node@5.0.2
  aws-ecr: circleci/aws-ecr@8.1.2

parameters:
  deploy_build:
    type: boolean
    default: false
  deploy_time_minutes:
    type: integer
    default: 60

jobs:
  build-test-api:
    executor:
      name: node/default
      tag: 16.13.1
    steps:
      - checkout
      - node/install-packages:
        app-dir: ./api
        pkg-manager: npm

workflows:
  build:
    jobs:
      - build-test-api:
      # - build-test-ui:
  # build-deploy:
  #   jobs:
  #     - aws-ecr/build-and-push-image:
  #         repo: test-ecr
  #         tag: "latest,v0.1.${CIRCLE_BUILD_NUM}"
  #         dockerfile: Dockerfile
  #         path: ./release
