version: 2.1
orbs:
  node: circleci/node@5.0.2
  aws-ecr: circleci/aws-ecr@8.1.2

workflows:
  default:
    jobs:
      - aws-ecr/build-and-push-image
        repo: test-ecr
        tag: "latest,v0.1.%{CIRCLE_BUILD_NUM}"
        dockerfile: release/dockerfile
        path: .
